title: Text Adventure
short_title: Text Adventure
description: Text Adventure
baseurl: "/text-adventure"
url: "https://funwithbrains.github.io/text-adventure/"
repository: funwithbrains/text-adventure.github.io.git

markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - private
  - .vscode

compress_html:
  clippings: all

defaults:
  - scope:
      path: ""
    values:
      mainScript: "/assets/scripts/main.js"
